apiVersion: apps/v1
kind: Deployment
metadata:
  name: casestudy-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casestudy-generator
  template:
    metadata:
      labels:
        app: casestudy-generator
    spec:
      containers:
      - name: casestudy-generator
        image: devopsproject-casestudygenerator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: casestudy-config
        volumeMounts:
        - name: sqlite-data
          mountPath: /app/prisma/data
      volumes:
      - name: sqlite-data
        hostPath:
          path: /data/casestudy-generator/sqlite 
          type: DirectoryOrCreate
